### PR TITLE
Adding Jaguar Land Rover partner page

### PR DESCRIPTION
**Pull request by pknight03**
There will be one more update just to add a couple of the team hashtags.

### CODE REVIEW

**Comment by dalekunce** [comment]
@pknight03 this looks good but for any new partners we need to use the Microsoft template, which needs to be made fully into a template first.

This is not ready to merge, if you need this in the next week please contact me offline.

**Comment by pknight03** [comment]
@dalekunce 
Pinged you via email.
Thanks,
Paul

**Comment by pknight03** [comment]
@dalekunce Updated the md file if you dont manage to get the new page done in time, so a simple PR :)

**Comment by dalekunce** [comment]
Thanks for merging @danbjoseph

**Pull request merged**
