### PR TITLE
refac: moved to new api url

### PR DESCRIPTION
**Pull request by ElJocho**
- [x] set final dashboard url
- [x] set final api url

### CODE REVIEW

**Comment by dakotabenjamin** [comment]
So far looks good! Tested locally, let me know when its ready for full review. 

as a note, probably you will want to remove the changes in `_partner` directory before we can merge.

**Comment by ElJocho** [comment]
-> moved back to draft since we just separated the /stats endpoint into /stats for one hashtag and /stats/hashtags for multiple hashtags. This change is not yet live in the prod api

**Review by dakotabenjamin — COMMENTED** [review]
I noticed that wildcards don't disaggregate in the graphs: 

old API: 
image

New API: 
image

If this is intended, then @nicolelaine we will need to manually change partners' hashtags lists from using wildcards (`*`) and list out every hashtag.

**Comment by ElJocho** [comment]
Interesting, nice catch! I did not notice that this is the intended behavior, I think we could easily adapt that for the /stats/hashtags endpoint, since currently it is only used by this site. I will follow up with more on this later this day :).

**Comment by ElJocho** [comment]
We will adjust the endpoint tomorrow, so that it will dis-aggregate the hashtags if possible :+1:

**Comment by Hagellach37** [comment]
the endpoint has been adjusted.

https://stats.now.ohsome.org/api/stats/hashtags/missingmaps,hotosm-project-*?startdate=2022-08-25T09:55:42.000Z&enddate=2023-08-25T09:55:42.000Z

**Review by dakotabenjamin — APPROVED** [review]

**Pull request merged**
