### PR TITLE
Make Partners easier to edit with Prose

### PR DESCRIPTION
**Pull request by DylanMoriarty**
Adds a prose.yml file to allow for nicer partner page editing in prose.io. Modifies the format of the pages very slightly and updates the readme accordingly.

### CODE REVIEW

**Comment by dalekunce** [comment]
should this be merged in now?

**Comment by dalekunce** [comment]
@DylanMoriarty can we merge this?

**Comment by DylanMoriarty** [comment]
Almost good to go. I need to fix some merge conflicts with the develop branch quick here.

screencapture-prose-io-1464990475438

Prose can't support complex write ups like we have for the projects section, so that will have to remain as  editable RAW metadata.

**Comment by DylanMoriarty** [comment]
@dalekunce good to go!

**Pull request merged**
